version: '3.8'

services:
  carea-backend-api:
    container_name: carea-backend-api
    restart: unless-stopped
    cpu_count: 1
    image: carea-backend:latest
    env_file: ./.env.production.local

    networks:
      - pg-dev
      - redpanda
      - traefik
      - redis

    ports:
      - 56000:4000
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.carea-api.rule=Host(`carea-api.p.kariukigeorge.me`)
      - traefik.http.routers.carea-api.tls=true
      - traefik.http.routers.carea-api.tls.certresolver=lets-encrypt
      - traefik.port=54500
networks:
  pg-dev:
    external: true

  redpanda:
    external: true
  redis:
    external: true
  traefik:
    external: true
