jobs:
  build:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: node --version
      - run: yarn
      - run: yarn test
          
workflows:
  build-and-test:
    jobs:
      - build